// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// check_digit.cpp
cpp11::logicals valid_checksum(cpp11::strings chis);
extern "C" SEXP _phsmethods_valid_checksum(SEXP chis) {
  BEGIN_CPP11
    return cpp11::as_sexp(valid_checksum(cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(chis)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_phsmethods_valid_checksum", (DL_FUNC) &_phsmethods_valid_checksum, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_phsmethods(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
