// Generated by cppally: do not edit by hand
// clang-format off


#include <cppally/r_dispatch.h>
#include <cppally.hpp>
#include <R_ext/Visibility.h>


using namespace cppally;
using internal::cpp_to_r;
using internal::r_to_cpp;
using internal::dispatch_template_impl;

// chi_check.cpp
r_vector<r_str> cpp_chi_check(const r_vector<r_str>& x, bool check_mod11, bool check_mod10);
extern "C" SEXP _phsmethods_cpp_chi_check(SEXP x, SEXP check_mod11, SEXP check_mod10) {
  BEGIN_CPPALLY
  return cpp_to_r(::cpp_chi_check(r_to_cpp<const r_vector<r_str>&>(x), r_to_cpp<bool>(check_mod11), r_to_cpp<bool>(check_mod10)));
  END_CPPALLY
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_phsmethods_cpp_chi_check", (DL_FUNC) &_phsmethods_cpp_chi_check, 3},
    {NULL, NULL, 0}
};
}


extern "C" attribute_visible void R_init_phsmethods(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
