// Generated by cppally: do not edit by hand
// clang-format off


#include <cppally/r_dispatch.h>
#include <cppally.hpp>
#include <R_ext/Visibility.h>


using namespace cppally;
using internal::cpp_to_r;
using internal::r_to_cpp;
using internal::dispatch_template_impl;

// code.cpp
void dummy();
extern "C" SEXP _phsmethods_dummy() {
  BEGIN_CPPALLY
  ::dummy();
  return R_NilValue;
  END_CPPALLY
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_phsmethods_dummy", (DL_FUNC) &_phsmethods_dummy, 0},
    {NULL, NULL, 0}
};
}


extern "C" attribute_visible void R_init_phsmethods(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
