# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    paths: ["R/**"]
  pull_request:
    paths: ["R/**"]

name: Document

jobs:
  document:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::roxygen2
          needs: roxygen2

      - name: Document
        run: roxygen2::roxygenise()
        shell: Rscript {0}

      - name: Commit and create a Pull Request on master
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Update documentation"
          branch: document_master
          delete-branch: true
          title: Additional documentation for master branch
          labels: documentation,Maintainance
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}

      - name: Commit and push changes on all other branches
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update documentation"
